# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  schedule:
    - cron: "03 03 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yaml"
      - "**.yml"
      - "!**R-CMD-check.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yaml"
      - "**.yml"
      - "!**R-CMD-check.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-24.04, r: '4.0', rspm: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"}
          - {os: ubuntu-24.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"}
          - {os: ubuntu-24.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"}

    env:
      _R_CHECK_CRAN_INCOMING_: true # Seemingly not set by --as-cran
      _R_CHECK_FORCE_SUGGESTS_: false # CRAN settings
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      _R_CHECK_THINGS_IN_CHECK_DIR_: false
      R_REMOTES_STANDALONE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - name: Temporarily bump package version
        run: |
          old_version=$(grep "Version:" DESCRIPTION | awk '{print $2}')
          if [[ $(echo "$old_version" | tr -cd '.' | wc -c) -eq 2 ]]; then
            new_version="${old_version}.9999"
            if [[ "$RUNNER_OS" == "macOS" ]]; then
              sed -i "" "s/Version: .*/Version: ${new_version}/" DESCRIPTION
            else
              sed -i "s/Version: .*/Version: ${new_version}/" DESCRIPTION
            fi
          fi
          echo "Current package version is now: $(grep "Version:" DESCRIPTION | awk '{print $2}')"
        shell: bash

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Set up R dependencies (Windows)
        if: runner.os == 'Windows'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: |
            check
            coverage


      - name: Set up R dependencies (R 4.0)
        if: matrix.config.r == '4.0'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            googledrive@2.0.0
            btergm@1.10.6
            sparsevctrs@0.3.3
            mvinfluence@0.9.0
            Sleuth2@1.0-0
            modelsummary@1.4.3
            plm@2.4-3
            heplots@1.6.2
            ggstats@0.2.1
            ggsurvfit@1.0.0
            subplex@1.7
            tidycmprsk@1.0.0
            statnet.common@4.11.0
            collapse@1.6.5
            clock@0.7.3
            qqconf@1.3.2
            dfidx@0.0-4
            gsl@2.1-7
            prodlim@2019.11.13
            gtsummary@1.6.3
            survival@3.7-0
            pals@1.7
            dials@1.4.0
            infer@1.0.0
            tune@0.1.6
            workflowsets@0.1.0
            tidymodels@0.1.4
            gdtools@0.2.3
            rmcorr@0.4.5
            hardhat@1.4.1
            WRS2@1.1-3
            dotCall64@1.1-1
            fields@13.3
            correlation@0.7.1
            ggdist@3.0.1
            ggside@0.2.2
            randomForest@4.6-14
            fastICA@1.2-2
            parsnip@1.3.0
            workflows@0.2.5
            effectsize@0.6.0.1
            performance@0.14.0
            see@0.9.0
            gamlss@5.3-1
            gamm4@0.2-6
            unmarked@1.1.1
            datawizard@1.2.0
            spam@2.7-0
            GGally@2.1.2
            bayesplot@1.9.0
            estimability@1.4.1
            MuMIn@1.43.17
            pbkrtest@0.5.1
            recipes@1.0.10
            slider@0.3.2
            emmeans@1.7.5
            latentnet@2.11.0
            Bergm@5.0.4
            ergm.multi@0.1.2
            ergm.count@4.1.1
            ergm@4.3.2
            gam@1.20.2
            metafor@3.4-0
            modeldata@1.0.0
            rsample@1.0.0
            survey@4.1-1
            broom.helpers@1.14.0
            broom@1.0.8
            Matrix@1.6-5
            VGAMextra@0.0-5
            VGAMdata@1.1-6
            VGAM@1.1-6
            duckdb@1.2.1
            Hmisc@5.1-1
            ggplot2@3.5.2
            htmlTable@2.4.1
            rio@1.1.1
            rms@5.1-4
            arrow@15.0.1
            readODS@2.3.1
            tzdb@0.5.0
            rvest@1.0.4
            gh@1.4.1
            svglite@2.1.3
            scales@1.3.0
            magick@2.8.5
            purrr@1.0.2
            bench@1.1.3
            waldo@0.5.3
            testthat@3.2.1
            cpp11@0.5.0
            downlit@0.4.3
            pkgdown@2.0.9
            profvis@0.3.8
            gtable@0.3.6
            vdiffr@1.0.7
            evaluate@0.23
            knitr@1.45
            httr2@1.0.1
            rjson@0.2.20
            usethis@3.1.0
            XML@3.99-0.3
          needs: |
            check

      - name: Set up R dependencies (Non-Windows)
        if: runner.os != 'Windows' && matrix.config.r != '4.0'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: |
            check

      - name: Check package
        uses: r-lib/actions/check-r-package@v2

      - name: Code coverage
        if: runner.os == 'Windows'
        run: |
          covr::codecov()
        shell: Rscript {0}

      - name: Notify on failure
        if: failure() && github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 8,
              body: 'Scheduled workflow has failed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            });
